### ISSUE TITLE
Complete Day 9

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#10]
Complete Day 9 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 9 - 100 Days of Code: Casting](https://www.youtube.com/watch?v=4hNQsFN9ki8&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=11) YouTube video. 
- [ ] **Required:** Successfully code the Day 9 Challenge. 
- [ ] **Optional:** Share your code with others.
