### ISSUE TITLE
Complete Day 10

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#11]
Complete Day 10 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 10 - 100 Days of Code: A bit of math](https://www.youtube.com/watch?v=8pzLxVej3_g&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=12) YouTube video. 
- [ ] **Required:** Successfully code the Day 10 Challenge. 
- [ ] **Optional:** Share your code with others.
