### ISSUE TITLE
Complete Day 11

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#12]
Complete Day 11 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 11 - 100 Days of Code: Project Day! How many seconds in a year](https://www.youtube.com/watch?v=pKRE-W9HGNs&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=13) YouTube video. 
- [ ] **Required:** Successfully code the Day 11 Challenge. 
- [ ] **Optional:** Share your code with others.
