### ISSUE TITLE
Complete Day 12

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#13]
Complete Day 12 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 12 - 100 Days of Code: Debug my code!](https://www.youtube.com/watch?v=MHY4Ei2U60k&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=14) YouTube video. 
- [ ] **Required:** Successfully code the Day 12 Challenge. 
- [ ] **Optional:** Share your code with others.
