### ISSUE TITLE
Complete Day 13

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#14]
Complete Day 13 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 13 - 100 Days of Code: Project: What grade did I get?](https://www.youtube.com/watch?v=fOFWkmAyCHY&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=15) YouTube video. 
- [ ] **Required:** Successfully code the Day 13 Challenge. 
- [ ] **Optional:** Share your code with others.
