### ISSUE TITLE
Complete Day 14

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#15]
Complete Day 14 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 14 - 100 Days of Code: 2 player rock, paper, scissor!](https://www.youtube.com/watch?v=5YP8QIpR1SQ&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=16) YouTube video. 
- [ ] **Required:** Successfully code the Day 14 Challenge. 
- [ ] **Optional:** Share your code with others.
