### ISSUE TITLE
Complete Day 15

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#16]
Complete Day 15 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 15: 100 Days of Code: Loops](https://www.youtube.com/watch?v=AwCI7IG-i38&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=17) YouTube video. 
- [ ] **Required:** Successfully code the Day 15 Challenge. 
- [ ] **Optional:** Share your code with others.
