### ISSUE TITLE
Complete Day #

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#17]
Complete Day 16 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 16: 100 Days of Code: While True loop](https://www.youtube.com/watch?v=cuseM3bReT4&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=18) YouTube video. 
- [ ] **Required:** Successfully code the Day 16 Challenge. 
- [ ] **Optional:** Share your code with others.
