### ISSUE TITLE
Complete Day #

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#18]
Complete Day 17 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 17: 100 Days of Code: Continue Statement](https://www.youtube.com/watch?v=e5048kp-ogk&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=19) YouTube video. 
- [ ] **Required:** Successfully code the Day 17 Challenge. 
- [ ] **Optional:** Share your code with others.
