### ISSUE TITLE
Complete Day 18

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#19]
Complete Day 18 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 18: 100 Days of Code: Project Day! Guess the Number Guessing Game](https://www.youtube.com/watch?v=ox5KGtrXs5E&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=20) YouTube video. 
- [ ] **Required:** Successfully code the Day 18 Challenge. 
- [ ] **Optional:** Share your code with others.
