### ISSUE TITLE
Complete Day 19

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#20]
Complete Day 19 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 19: 100 Days of Code: For Loop](https://www.youtube.com/watch?v=0n65nmmuCSI&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=21) YouTube video. 
- [ ] **Required:** Successfully code the Day 19 Challenge. 
- [ ] **Optional:** Share your code with others.
