### ISSUE TITLE
Complete Day 20

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#21]
Complete Day 20 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 20: 100 Days of Code: Range](https://www.youtube.com/watch?v=cstyIsl2Q6s&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=22) YouTube video. 
- [ ] **Required:** Successfully code the Day 20 Challenge. 
- [ ] **Optional:** Share your code with others.
