### ISSUE TITLE
Complete Day 21

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#22]
Complete Day 21 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 21: 100 Days of Code: Project Day! Build a Math Facts Game](https://www.youtube.com/watch?v=rfK_QXsf2PA) YouTube video. 
- [ ] **Required:** Successfully code the Day 21 Challenge. 
- [ ] **Optional:** Share your code with others.
