### ISSUE TITLE
Complete Day 22

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#23]
Complete Day 22 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 22: 100 Days of Code: Libraries](https://www.youtube.com/watch?v=KQ0hAk_lXCQ) YouTube video. 
- [ ] **Required:** Successfully code the Day 22 Challenge. 
- [ ] **Optional:** Share your code with others.
