### ISSUE TITLE
Complete Day 23

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#24]
Complete Day 23 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 23: 100 Days of Code: Subroutines](https://www.youtube.com/watch?v=gogQkRaXPmA) YouTube video. 
- [ ] **Required:** Successfully code the Day 23 Challenge. 
- [ ] **Optional:** Share your code with others.
