### ISSUE TITLE
Complete Day 24

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#25]
Complete Day 24 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 24: 100 Days of Code: Parameters](https://www.youtube.com/watch?v=AEpcNiqV73k) YouTube video. 
- [ ] **Required:** Successfully code the Day 24 Challenge. 
- [ ] **Optional:** Share your code with others.
