### ISSUE TITLE
Complete Day 25

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#26]
Complete Day 25 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 25: 100 Days of Code: Return Command](https://www.youtube.com/watch?v=jPF_tAnYY44) YouTube video. 
- [ ] **Required:** Successfully code the Day 25 Challenge. 
- [ ] **Optional:** Share your code with others.
