### ISSUE TITLE
Complete Day 26

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#27]
Complete Day 26 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 26: 100 Days of Code: More Libraries](https://www.youtube.com/watch?v=_IGpC-sA7M4) YouTube video. 
- [ ] **Required:** Successfully code the Day 26 Challenge. 
- [ ] **Optional:** Share your code with others.
