### ISSUE TITLE
Complete Day 27

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#28]
Complete Day 27 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 27: 100 Days of Code: Epic Character Battle, Part 1](https://www.youtube.com/watch?v=jCtk6DZLHoQ) YouTube video. 
- [ ] **Required:** Successfully code the Day 27 Challenge. 
- [ ] **Optional:** Share your code with others.
