### ISSUE TITLE
Complete Day 28

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#29]
Complete Day 28 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 28: 100 Days of Code: Project Day: Epic Character Battle, Part 2](https://www.youtube.com/watch?v=VVMqAAMjO_I) YouTube video. 
- [ ] **Required:** Successfully code the Day 28 Challenge. 
- [ ] **Optional:** Review the [Day 28: Solution](https://www.youtube.com/watch?v=qH8StNJXyM0) YouTube video. 
- [ ] **Optional:** Share your code with others.
