### ISSUE TITLE
Complete Day 2

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#3]
Complete Day 2 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 2 - 100 Days of Code: Input & Variables](https://www.youtube.com/watch?v=b5tFeJ0Ol2Y&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=4) YouTube video. 
- [ ] **Required:** Successfully code the Day 2 Challenge. 
- [ ] **Optional:** Share your code with others.
