### ISSUE TITLE
Complete Day 29

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#30]
Complete Day 29 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 29: 100 Days of Code: The Secrets of `print`](https://www.youtube.com/watch?v=xeqG1AgvDLI) YouTube video. 
- [ ] **Required:** Successfully code the Day 29 Challenge. 
- [ ] **Optional:** Review the [Day 29: Solution](https://www.youtube.com/watch?v=5hKXVNaorxs) YouTube video. 
- [ ] **Optional:** Share your code with others.
