### ISSUE TITLE
Complete Day 30

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#31]
Complete Day 30 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 30: 100 Days of Code: f-strings](https://www.youtube.com/watch?v=uaOmD6XRt3A) YouTube video. 
- [ ] **Required:** Successfully code the Day 30 Challenge. 
- [ ] **Optional:** Review the [Day 30: Solution](https://www.youtube.com/watch?v=JBJfN4aOyOY) YouTube video. 
- [ ] **Optional:** Share your code with others.
