### ISSUE TITLE
Complete Day 31

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#32]
Complete Day 31 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 31: 100 Days of Code: Project Day: Create User Interfaces with Color](https://www.youtube.com/watch?v=rV6en_DUBZk) YouTube video. 
- [ ] **Required:** Successfully code the Day 31 Challenge. 
- [ ] **Optional:** Review the [Day 31: Solution](https://www.youtube.com/watch?v=zKMPQLoh0zA) YouTube video. 
- [ ] **Optional:** Share your code with others.
