### ISSUE TITLE
Complete Day 32

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#33]
Complete Day 32 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 32: 100 Days of Code: Lists](https://www.youtube.com/watch?v=sylq300J9EM) YouTube video. 
- [ ] **Required:** Successfully code the Day 32 Challenge. 
- [ ] **Optional:** Review the [Day 32: Solution](https://www.youtube.com/watch?v=qTyCw0q8a70) YouTube video. 
- [ ] **Optional:** Share your code with others.
