### ISSUE TITLE
Complete Day 33

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#34]
Complete Day 33 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 33: 100 Days of Code: Dynamic Lists](https://www.youtube.com/watch?v=O26Y99VRsgQ) YouTube video. 
- [ ] **Required:** Successfully code the Day 33 Challenge. 
- [ ] **Optional:** Review the [Day 33: Solution](https://www.youtube.com/watch?v=Csi3vGGYwuk) YouTube video. 
- [ ] **Optional:** Share your code with others.
