### ISSUE TITLE
Complete Day 34

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#35]
Complete Day 34 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 34: 100 Days of Code: Pretty Printing](https://www.youtube.com/watch?v=Pg4QMSTTNIw) YouTube video. 
- [ ] **Required:** Successfully code the Day 34 Challenge. 
- [ ] **Optional:** Review the [Day 34: Solution](https://www.youtube.com/watch?v=yAZ8Mf1-knA) YouTube video. 
- [ ] **Optional:** Share your code with others.
