### ISSUE TITLE
Complete Day 35

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#36]
Complete Day 35 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 35: 100 Days of Code: Project Day: The ULTIMATE List Maker](https://www.youtube.com/watch?v=jX0UBq0u1Co) YouTube video. 
- [ ] **Required:** Successfully code the Day 35 Challenge. 
- [ ] **Optional:** Review the [Day 35: Solution](https://www.youtube.com/watch?v=uqxm5iyGNbU) YouTube video. 
- [ ] **Optional:** Share your code with others.
