### ISSUE TITLE
Complete Day 36

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#37]
Complete Day 36 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 36: 100 Days of Code: String Manipulation](https://www.youtube.com/watch?v=2XBhtE3Pl6M) YouTube video. 
- [ ] **Required:** Successfully code the Day 36 Challenge. 
- [ ] **Optional:** Review the [Day 36: Solution](https://www.youtube.com/watch?v=Co-jqvo0cDI) YouTube video. 
- [ ] **Optional:** Share your code with others.
