### ISSUE TITLE
Complete Day 37

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#38]
Complete Day 37 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 37: 100 Days of Code: String Slicing](https://www.youtube.com/watch?v=0fJNVerQaNI) YouTube video. 
- [ ] **Required:** Successfully code the Day 37 Challenge. 
- [ ] **Optional:** Review the [Day 37: Solution](https://www.youtube.com/watch?v=caZraiOMhlY) YouTube video. 
- [ ] **Optional:** Share your code with others.
