### ISSUE TITLE
Complete Day 38

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#39]
Complete Day 38 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 38: 100 Days of Code: Strings and Loops](https://www.youtube.com/watch?v=twzCfSvyte8) YouTube video. 
- [ ] **Required:** Successfully code the Day 38 Challenge. 
- [ ] **Optional:** Review the [Day 38: Solution](https://www.youtube.com/watch?v=d_ye0gZF1y8) YouTube video. 
- [ ] **Optional:** Share your code with others.
