### ISSUE TITLE
Complete Day 3

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#4]
Complete Day 3 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 3 - 100 Days of Code: Concatenation](https://www.youtube.com/watch?v=G7r_1NQrSm0&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=5) YouTube video. 
- [ ] **Required:** Successfully code the Day 3 Challenge. 
- [ ] **Optional:** Share your code with others.
