### ISSUE TITLE
Complete Day 39

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#40]
Complete Day 39 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 39: 100 Days of Code: Project Day: Hangman!](https://www.youtube.com/watch?v=g2Go3XS3VZg) YouTube video. 
- [ ] **Required:** Successfully code the Day 39 Challenge. 
- [ ] **Optional:** Review the [Day 39: Solution](https://www.youtube.com/watch?v=UH3vIwOPXA0) YouTube video. 
- [ ] **Optional:** Share your code with others.
