### ISSUE TITLE
Complete Day 40

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#41]
Complete Day 40 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 40: 100 Days of Code: Dictionaries](https://www.youtube.com/watch?v=TkKsEq6ODNs) YouTube video. 
- [ ] **Required:** Successfully code the Day # Challenge. 
- [ ] **Optional:** Review the [Day 40: Solution](https://www.youtube.com/watch?v=FXegOVAT2e4) YouTube video. 
- [ ] **Optional:** Share your code with others.
