### ISSUE TITLE
Complete Day 4

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#5]
Complete Day 4 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 4 - 100 Days of Code: Project Day! Write your own story](https://www.youtube.com/watch?v=oakgvGNYQoQ&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=6) YouTube video. 
- [ ] **Required:** Successfully code the Day 4 Challenge. 
- [ ] **Optional:** Share your code with others.
