### ISSUE TITLE
Complete Day 5

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#6]
Complete Day 5 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 5 - 100 Days of Code: If statements + Else](https://www.youtube.com/watch?v=Wmn9yze6m5U&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=7) YouTube video. 
- [ ] **Required:** Successfully code the Day 5 Challenge. 
- [ ] **Optional:** Share your code with others.
