### ISSUE TITLE
Complete Day 6

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#7]
Complete Day 6 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 6 - 100 Days of Code: Elif](https://www.youtube.com/watch?v=Dm8lRtcnh0o&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=8) YouTube video. 
- [ ] **Required:** Successfully code the Day 6 Challenge. 
- [ ] **Optional:** Share your code with others.
