### ISSUE TITLE
Complete Day 7

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#8]
Complete Day 7 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 7 - 100 Days of Code: Nesting](https://www.youtube.com/watch?v=Abk1jPdnMIc&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=9) YouTube video. 
- [ ] **Required:** Successfully code the Day 7 Challenge. 
- [ ] **Optional:** Share your code with others.
