### ISSUE TITLE
Complete Day 8

### ISSUE THREAD

**Issue by tempestwrecker** [tempestwrecker/replits-100-days-of-python#9]
Complete Day 8 of Replit's 100 Days of Python. 

# Task List 
- [ ] **Required:** Watch the [Day 8 - 100 Days of Code: Project Day! Affirmations / Insults](https://www.youtube.com/watch?v=3SXW63IIs4I&list=PLto9KpJAqHMQNY3XP0JqLs7NyeU_dnNj0&index=10) YouTube video. 
- [ ] **Required:** Successfully code the Day 8 Challenge. 
- [ ] **Optional:** Share your code with others.
